---
title: "Economic Relational Equilibrium"
author: "Sean Rodgers"
output:
    html_document:
        toc: true
        toc_float: 
            collapsed: false
            smooth_scroll: true
---
#Economic Relational Equilibrium

We relate to people in many different ways.  The way we view people can effect how we treat them and how we relate to them as well. 

Being on the same team means that you are all working for the same goals.  Think of it like a stage with performers.  There can only be so many people on stage doing their thing.  Sometimes there is a single important person in the light.  This person, what ever their role, has center stage as they would say.  If any of the other performers cause a scene or distraction, the performer at the center of the stage's message might not be heard or frustrated.  This is how many of our teams work, there are times when there is one person at center stage and our job is to support them as best that we can.

This can cause undue strife between two parties.  Where one feels cheated and used and the other never feels like they are getting enough out of the relation ship. 

Whether the ledger contain money, favors, or kind words in exchange; the relationship status cannot be based on the balance sheet.  The mental work and emotional strain this causes is not healthy.
